export default {
  title: 'Search with AI',
  theme: 'Theme',
  ask: 'Me',
  answer: 'Answer',
  reasoning: 'Deep Thinking',
  related: 'Related',
  sources: 'Sources',
  media: 'Media',
  copy: 'Copy',
  reload: 'Reload',
  share: 'Share',
  search: 'Engine',
  newChat: 'New Q&A',
  sogou: 'Sogou',
  chatglm: 'ChatGLM',
  bing: 'Bing',
  google: 'Google',
  searxng: 'SearXNG',
  llm: 'LLM',
  chat: 'Continue Q&A',
  back: 'Back Home',
  language: 'Language',
  settings: 'Settings',
  selectModel: 'Select LLM',
  selectLanguage: 'Select Language',
  selectEngine: 'Select Search Engine',
  localModel: 'Local LLM',
  localProvider: 'Local Provider',
  selectProvider: 'Select Provider',
  provider: 'PROVIDER',
  enableLocalModel: 'Enable Local LLM',
  warning: 'Content is generated by AI and accuracy cannot be guaranteed',
  addToSearchEngine: 'Add to Browser Search',
  message: {
    queryError: 'Query error',
    copyError: 'Copy failed',
    noSelect: 'Not selected yet',
    sourceError: 'Failed to obtain information',
    shareSuccess: 'Sharing link copied to clipboard.',
    noRelated: 'No related questions found',
    success: 'successful!',
    searchEngineAdded: 'Search engine successfully added to your browser',
    searchEngineError: 'Failed to add search engine to your browser',
    chromeInstructions: 'For Chrome: Right-click the address bar > Manage search engines > Add > Enter "Search with AI" and paste the current URL with "?q=%s" at the end',
    browserNotSupported: 'Your browser does not support adding custom search engines'
  },
  category: {
    general: 'General',
    science: 'Science',
    images: 'Images',
    videos: 'Videos'
  },
  mode: {
    simple: 'Simple',
    deep: 'Deep',
    research: 'Research'
  },
  tips: {
    search: 'Ask a question.',
    continue: 'Continue to ask based on the current context.'
  },
  btn: {
    clear: 'Clear history'
  }
};
